#load libraries
library(tidyr)
library(ragg)
library(svglite)
library(ggpubr)
suppressPackageStartupMessages(install.packages(janitor))
suppressPackageStartupMessages(library(janitor))
suppressPackageStartupMessages(library(dplyr))
library(ggplot2)
suppressPackageStartupMessages(library(palmerpenguins))
library(lattice)
install.packages("latexpdf")
library(latexpdf)

#For generating images
suppressPackageStartupMessages(install.packages("ragg"))
suppressPackageStartupMessages(install.packages("svglite"))
suppressPackageStartupMessages(library(ragg))
suppressPackageStartupMessages(library(svglite))
suppressPackageStartupMessages(install.packages("png"))
suppressPackageStartupMessages(install.packages("ggimage"))
suppressPackageStartupMessages(install.packages("jpeg"))
library(png)
library(grid)
library(ggplot2)
library(ggimage)
library(jpeg)
